# Generated by Django 4.1.6 on 2023-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="likes",
            field=models.IntegerField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
