# Generated by Django 4.1.6 on 2023-02-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blog_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="blah", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog", name="likes", field=models.IntegerField(default=0),
        ),
    ]
